// Code generated by goctl. DO NOT EDIT!
// Source: message.proto

package server

import (
	"context"

	"github.com/quanxiang-cloud/flow/internal/logic"
	"github.com/quanxiang-cloud/flow/internal/svc"
	"github.com/quanxiang-cloud/flow/pb"
)

// EventServer EventServer
type EventServer struct {
	svcCtx *svc.ServiceContext
}

// NewEventServer NewEventServer
func NewEventServer(svcCtx *svc.ServiceContext) *EventServer {
	return &EventServer{
		svcCtx: svcCtx,
	}
}

// Publish Publish
func (s *EventServer) Publish(ctx context.Context, in *pb.EventReq) (*pb.EventResp, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}
